AcunMedyaRestaurantly/Controllers/DashboardController.cs
using AcunMedyaRestaurantly.Context;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AcunMedyaRestaurantly.Controllers
{
    [Authorize]
    public class DashboardController : Controller
    {
        RestaurantlyContext db = new RestaurantlyContext();
        public ActionResult Index()
        {
            ViewBag.ProductCount = db.Products.Count();
            ViewBag.CategoryCount = db.Categories.Count();
            ViewBag.ChefCount = db.Chefs.Count();
            ViewBag.SpecialCount = db.Specials.Count();
            ViewBag.MessageCount = db.Contacts.Count();
            ViewBag.NotificationCount = db.Notifications.Count();
            ViewBag.ReservationCount = db.Reservations.Count();
            ViewBag.TestimonialCount = db.Testimonials.Count();
            return View();
        }
        public PartialViewResult ReservationPartial()
        {
            var value = db.Reservations.ToList();
            return PartialView(value);
        }
    }
}

AcunMedyaRestaurantly/Views/Dashboard/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/AdminLayout/Index.cshtml";
}

<div class="container-fluid mt-3">
    <div class="row">
        <div class="col-lg-3 col-sm-6">
            <div class="card gradient-1">
                <div class="card-body">
                    <h3 class="card-title text-white">Yemek Sayısı</h3>
                    <div class="d-inline-block">
                        <h2 class="text-white">@ViewBag.ProductCount</h2>
                        <p class="text-white mb-0">Ürünler</p>
                    </div>
                    <span class="float-right display-5 opacity-5"><i class="fa fa-shopping-cart"></i></span>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-sm-6">
            <div class="card gradient-2">
                <div class="card-body">
                    <h3 class="card-title text-white">Kategori Sayısı</h3>
                    <div class="d-inline-block">
                        <h2 class="text-white">@ViewBag.CategoryCount</h2>
                        <p class="text-white mb-0">Kategoriler</p>
                    </div>
                    <span class="float-right display-5 opacity-5"><i class="fa fa-money"></i></span>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-sm-6">
            <div class="card gradient-3">
                <div class="card-body">
                    <h3 class="card-title text-white">Şef Sayısı</h3>
                    <div class="d-inline-block">
                        <h2 class="text-white">@ViewBag.ChefCount</h2>
                        <p class="text-white mb-0">Şefler</p>
                    </div>
                    <span class="float-right display-5 opacity-5"><i class="fa fa-users"></i></span>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-sm-6">
            <div class="card gradient-4">
                <div class="card-body">
                    <h3 class="card-title text-white">Spesiyal Sayısı</h3>
                    <div class="d-inline-block">
                        <h2 class="text-white">@ViewBag.SpecialCount</h2>
                        <p class="text-white mb-0">Spesiyaller</p>
                    </div>
                    <span class="float-right display-5 opacity-5"><i class="fa fa-heart"></i></span>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-3 col-sm-6">
            <div class="card gradient-5">
                <div class="card-body">
                    <h3 class="card-title text-white">Gelen Mesajlar</h3>
                    <div class="d-inline-block">
                        <h2 class="text-white">@ViewBag.MessageCount</h2>
                        <p class="text-white mb-0">Mesajlar</p>
                    </div>
                    <span class="float-right display-5 opacity-5"><i class="fa fa-shopping-cart"></i></span>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-sm-6">
            <div class="card gradient-6">
                <div class="card-body">
                    <h3 class="card-title text-white">Bildirim Sayısı</h3>
                    <div class="d-inline-block">
                        <h2 class="text-white">@ViewBag.NotificationCount</h2>
                        <p class="text-white mb-0">Bildirimler</p>
                    </div>
                    <span class="float-right display-5 opacity-5"><i class="fa fa-money"></i></span>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-sm-6">
            <div class="card gradient-7">
                <div class="card-body">
                    <h3 class="card-title text-white">Rezervasyon Sayısı</h3>
                    <div class="d-inline-block">
                        <h2 class="text-white">@ViewBag.ReservationCount</h2>
                        <p class="text-white mb-0">Rezervasyonlar</p>
                    </div>
                    <span class="float-right display-5 opacity-5"><i class="fa fa-users"></i></span>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-sm-6">
            <div class="card gradient-8">
                <div class="card-body">
                    <h3 class="card-title text-white">Referans Sayısı</h3>
                    <div class="d-inline-block">
                        <h2 class="text-white">@ViewBag.TestimonialCount</h2>
                        <p class="text-white mb-0">Referanslar</p>
                    </div>
                    <span class="float-right display-5 opacity-5"><i class="fa fa-heart"></i></span>
                </div>
            </div>
        </div>
    </div>

    @Html.Action("ReservationPartial", "Dashboard")
</div>

AcunMedyaRestaurantly/Views/Dashboard/ReservationPartial.cshtml
@model List<AcunMedyaRestaurantly.Entities.Reservation>
<div class="row">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-body">
                <div class="active-member">
                    <div class="table-responsive">
                        <table class="table table-xs mb-0">
                            <thead>
                                <tr>
                                    <th>Müşteri</th>
                                    <th>E-Posta</th>
                                    <th>Telefon</th>
                                    <th>Açıklama</th>
                                    <th>Durum</th>
                                    <th>Detaylar</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                <tr>
                                    <td>@item.Name</td>
                                    <td>@item.Email</td>
                                    <td>
                                        <span>@item.Phone</span>
                                    </td>
                                    <td>@item.Description</td>
                                    @if (item.ReservationStatus == "Onay Bekliyor")
                                    {
                                        <td><i class="fa fa-circle-o text-info  mr-2"></i> Onay Bekliyor...</td>
                                    }
                                    @if (item.ReservationStatus == "Onaylandı")
                                    {
                                        <td><i class="fa fa-circle-o text-success  mr-2"></i> Onaylandı...</td>
                                    }
                                    @if (item.ReservationStatus == "İptal Edildi")
                                    {
                                        <td><i class="fa fa-circle-o text-danger  mr-2"></i> Reddedildi...</td>
                                    }
                                    <td><a href="/Reservation/ReservationEdit/@item.ReservationId" class="btn btn-outline-info">Detaylar</a></td>
                                </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>