AcunMedyaRestaurantly/Controllers/AdminLayoutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AcunMedyaRestaurantly.Context;

namespace AcunMedyaRestaurantly.Controllers
{
    public class AdminLayoutController : Controller
    {
        RestaurantlyContext db = new RestaurantlyContext();
        public ActionResult Index()
        {
            return View();
        }
        public PartialViewResult PartialHead()
        {
            return PartialView();
        }
        public PartialViewResult PartialNavbar()
        {
            var mesajlar = db.Contacts.ToList();
            var values = db.Notifications.Where(x => x.isRead == false).ToList();
            var notificationIsReadyByFalseCount = values.Count();
            ViewBag.notificationIsReadyByFalseCount = notificationIsReadyByFalseCount;
            ViewBag.mesajlar = mesajlar;
            ViewBag.okunmamisMesajSayisi = db.Contacts.Where(x=>x.isRead==false).Count();
            return PartialView(values);
        }
        public PartialViewResult PartialSidebar()
        {
            return PartialView();
        }
        public PartialViewResult PartialFooter()
        {
            return PartialView();
        }
        public PartialViewResult PartialScript()
        {
            return PartialView();
        }
        public ActionResult NotificationStatusChangeToTrue(int id)
        {
            var notification = db.Notifications.Find(id);
            notification.isRead = true;
            db.SaveChanges();
            return RedirectToAction("Index", "Dashboard");
        }
        public ActionResult MessageStatusChangeToTrue(int id)
        {
            var message = db.Contacts.Find(id);
            message.isRead = true;
            db.SaveChanges();
            return RedirectToAction("Index","Dashboard");
        }
    }
}

AcunMedyaRestaurantly/Views/AdminLayout/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">

@Html.Action("PartialHead", "AdminLayout")

<body>

    <!--*******************
        Preloader start
    ********************-->
    <div id="preloader">
        <div class="loader">
            <svg class="circular" viewBox="25 25 50 50">
                <circle class="path" cx="50" cy="50" r="20" fill="none" stroke-width="3" stroke-miterlimit="10" />
            </svg>
        </div>
    </div>
    <!--*******************
        Preloader end
    ********************-->
    <!--**********************************
        Main wrapper start
    ***********************************-->
    <div id="main-wrapper">

        <!--**********************************
            Nav header start
        ***********************************-->
        <div class="nav-header">
            <div class="brand-logo">
                <a href="index.html">
                    <b class="logo-abbr"><img src="images/logo.png" alt=""> </b>
                    <span class="logo-compact"><img src="./images/logo-compact.png" alt=""></span>
                    <span class="brand-title">
                        <img src="images/logo-text.png" alt="">
                    </span>
                </a>
            </div>
        </div>
        <!--**********************************
            Nav header end
        ***********************************-->
        <!--**********************************
            Header start
        ***********************************-->
        @Html.Action("PartialNavbar", "AdminLayout")
        <!--**********************************
            Header end ti-comment-alt
        ***********************************-->
        <!--**********************************
            Sidebar start
        ***********************************-->
        @Html.Action("PartialSidebar", "AdminLayout")
        <!--**********************************
            Sidebar end
        ***********************************-->
        <!--**********************************
            Content body start
        ***********************************-->
        <div class="content-body">

            @RenderBody()
                    <!-- /# column -->
                    
                </div>
            </div>
            <!-- #/ container -->
        </div>
        <!--**********************************
            Content body end
        ***********************************-->
        <!--**********************************
            Footer start
        ***********************************-->
        @Html.Action("PartialFooter","Adminlayout") 
        <!--**********************************
            Footer end
        ***********************************-->
    </div>
    <!--**********************************
        Main wrapper end
    ***********************************-->
    <!--**********************************
        Scripts
    ***********************************-->
    @Html.Action("PartialScript", "AdminLayout")

</body>

</html>

AcunMedyaRestaurantly/Views/AdminLayout/PartialFooter.cshtml
<div class="footer">
    <div class="copyright">
        <p>Copyright &copy; Designed & Developed by <a href="https://themeforest.net/user/quixlab">Quixlab</a> 2025</p>
    </div>
</div>

AcunMedyaRestaurantly/Views/AdminLayout/PartialHead.cshtml
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>Restaurantly - Admin</title>
    <!-- Favicon icon -->
    <link rel="icon" type="~/Restaurantly/quixlab-master/quixlab-master/image/png" sizes="16x16" href="~/Restaurantly/quixlab-master/quixlab-master/images/favicon.png">
    <!-- Custom Stylesheet -->
    <link href="~/Restaurantly/quixlab-master/quixlab-master/css/style.css" rel="stylesheet">

</head>

AcunMedyaRestaurantly/Views/AdminLayout/PartialNavbar.cshtml
@model List<AcunMedyaRestaurantly.Entities.Notification>
<div class="header">
    <div class="header-content clearfix">
        <div class="nav-control">
            <div class="hamburger">
                <span class="toggle-icon"><i class="icon-menu"></i></span>
            </div>
        </div>
        <div class="header-left">
            <div class="input-group icons">
                <div class="input-group-prepend">
                    <span class="input-group-text bg-transparent border-0 pr-2 pr-sm-3" id="basic-addon1"><i class="mdi mdi-magnify"></i></span>
                </div>
                <input type="search" class="form-control" placeholder="Search Dashboard" aria-label="Search Dashboard">
                <div class="drop-down   d-md-none">
                    <form action="#">
                        <input type="text" class="form-control" placeholder="Search">
                    </form>
                </div>
            </div>
        </div>
        <div class="header-right">
            <ul class="clearfix">
                <li class="icons dropdown">
                    <a href="javascript:void(0)" data-toggle="dropdown">
                        <i class="mdi mdi-email-outline"></i>
                        <span class="badge gradient-1 badge-pill badge-primary">@ViewBag.okunmamisMesajSayisi</span>
                    </a>
                    <div class="drop-down animated fadeIn dropdown-menu">
                        <div class="dropdown-content-heading d-flex justify-content-between">
                            <span class="">@ViewBag.okunmamisMesajSayisi Yeni Mesaj</span>
                        </div>
                        <div class="dropdown-content-body">
                            <ul>
                                @foreach (var item in ViewBag.mesajlar)
                                {
                                    if (item.isRead == false)
                                    {
                                        <li class="notification-unread">
                                            <a href="/AdminLayout/MessageStatusChangeToTrue/@item.ContactId">
                                                <img class="float-left mr-3 avatar-img" src="https://kodgunlugum.com/wp-content/uploads/2018/09/whatsapp-okunmadi.png" alt="">
                                                <div class="notification-content">
                                                    <div class="notification-heading">@item.Name</div>
                                                    <div class="notification-timestamp">@item.SendDate</div>
                                                    <div class="notification-text">@item.Message</div>
                                                </div>
                                            </a>
                                        </li>
                                    }
                                    if (item.isRead = true)
                                    {
                                        <li>
                                            <a href="/AdminLayout/MessageStatusChangeToTrue/@item.ContactId">
                                                <img class="float-left mr-3 avatar-img" src="https://kodgunlugum.com/wp-content/uploads/2018/09/whatsapp-okundu.png" alt="">
                                                <div class="notification-content">
                                                    <div class="notification-heading">@item.Name</div>
                                                    <div class="notification-timestamp">@item.SendDate</div>
                                                    <div class="notification-text">@item.Message</div>
                                                </div>
                                            </a>
                                        </li>
                                    }
                                }
                            </ul>

                        </div>
                    </div>
                </li>
                <li class="icons dropdown">
                    <a href="javascript:void(0)" data-toggle="dropdown">
                        <i class="mdi mdi-bell-outline"></i>
                        <span class="badge badge-pill gradient-2 badge-primary">@ViewBag.notificationIsReadyByFalseCount</span>
                    </a>
                    <div class="drop-down animated fadeIn dropdown-menu dropdown-notfication">
                        <div class="dropdown-content-heading d-flex justify-content-between">
                            <span class="">@ViewBag.notificationIsReadyByFalseCount Yeni Bildirim</span>
                        </div>
                        <div class="dropdown-content-body">
                            <ul>
                                @foreach (var item in Model)
                                {
                                    <li>
                                        <a href="/AdminLayout/NotificationStatusChangeToTrue/@item.NotificationId">
                                            <span class="mr-3 avatar-icon bg-success-lighten-2" style="background-color:@item.IconColor"><i class="@item.Icon"></i></span>
                                            <div class="notification-content">
                                                <h6 class="notification-heading">@item.Title</h6>
                                                <span class="notification-text">@(((DateTime)item.Time).ToString("dd.MM.yyyy"))</span>
                                            </div>
                                        </a>
                                    </li>
                                }
                            </ul>
                        </div>
                    </div>
                </li>
                <li class="icons dropdown d-none d-md-flex">
                    <a href="javascript:void(0)" class="log-user" data-toggle="dropdown">
                        <span>English</span>  <i class="fa fa-angle-down f-s-14" aria-hidden="true"></i>
                    </a>
                    <div class="drop-down dropdown-language animated fadeIn  dropdown-menu">
                        <div class="dropdown-content-body">
                            <ul>
                                <li><a href="javascript:void()">English</a></li>
                                <li><a href="javascript:void()">Dutch</a></li>
                            </ul>
                        </div>
                    </div>
                </li>
                <li class="icons dropdown">
                    <div class="user-img c-pointer position-relative" data-toggle="dropdown">
                        <span class="activity active"></span>
                        <img src="@Session["Image"]" height="40" width="40" alt="">
                    </div>
                    <div class="drop-down dropdown-profile   dropdown-menu">
                        <div class="dropdown-content-body">
                            <ul>
                                <li>
                                    <a href="/Profiles/Index/"><i class="icon-user"></i> <span>Profilim</span></a>
                                </li>
                                <li>
                                    <a href="/Contact/ContactList"><i class="icon-envelope-open"></i> <span>Mesajlar</span> <div class="badge gradient-3 badge-pill badge-primary">@ViewBag.okunmamisMesajSayisi</div></a>
                                </li>

                                <hr class="my-2">
                                <li><a href="/Login/Logout"><i class="icon-key"></i> <span>Çıkış Yap!</span></a></li>
                            </ul>
                        </div>
                    </div>
                </li>
            </ul>
        </div>
    </div>
</div>

AcunMedyaRestaurantly/Views/AdminLayout/PartialScript.cshtml
<script src="~/Restaurantly/quixlab-master/quixlab-master/plugins/common/common.min.js"></script>
<script src="~/Restaurantly/quixlab-master/quixlab-master/js/custom.min.js"></script>
<script src="~/Restaurantly/quixlab-master/quixlab-master/js/settings.js"></script>
<script src="~/Restaurantly/quixlab-master/quixlab-master/js/gleek.js"></script>
<script src="~/Restaurantly/quixlab-master/quixlab-master/js/styleSwitcher.js"></script>

AcunMedyaRestaurantly/Views/AdminLayout/PartialSidebar.cshtml
<div class="nk-sidebar">
    <div class="nk-nav-scroll">
        <ul class="metismenu" id="menu">

            <li class="nav-label">Ana Sayfa</li>
            <li>
                <a href="/Profiles/Index/" aria-expanded="false">
                    <i class="icon-speedometer menu-icon"></i><span class="nav-text">Profilim</span>
                </a>
            </li>
            <li>
                <a href="/Dashboard/Index" aria-expanded="false">
                    <i class="icon-speedometer menu-icon"></i><span class="nav-text">Anasayfa</span>
                </a>
            </li>
            <li>
                <a href="/Statistic/Index" aria-expanded="false">
                    <i class="icon-speedometer menu-icon"></i><span class="nav-text">İstatistikler</span>
                </a>
            </li>

            <li class="nav-label">Mesaj ve Bildirimler</li>
            <li>
                <a href="/Contact/ContactList" aria-expanded="false">
                    <i class="icon-bell menu-icon"></i><span class="nav-text">Mesajlar</span>
                </a>
            </li>
            <li>
                <a href="/Notification/NotificationList" aria-expanded="false">
                    <i class="icon-bell menu-icon"></i><span class="nav-text">Bildirimler</span>
                </a>
            </li>

            <li class="nav-label">Değişkenler</li>
            <li>
                <a href="/About/AboutList" aria-expanded="false">
                    <i class="icon-trophy menu-icon"></i><span class="nav-text">Hakkında</span>
                </a>
            </li>
            <li>
                <a href="/Adress/AdressList" aria-expanded="false">
                    <i class="icon-trophy menu-icon"></i><span class="nav-text">Adres</span>
                </a>
            </li>
            <li>
                <a href="/Feature/FeatureList" aria-expanded="false">
                    <i class="icon-trophy menu-icon"></i><span class="nav-text">Başlık</span>
                </a>
            </li>

            <li class="nav-label">Veriler</li>
            <li>
                <a href="/Category/CategoryList" aria-expanded="false">
                    <i class="icon-badge menu-icon"></i><span class="nav-text">Kategoriler</span>
                </a>
            </li>
            <li>
                <a href="/Chef/ChefList" aria-expanded="false">
                    <i class="icon-badge menu-icon"></i><span class="nav-text">Şefler</span>
                </a>
            </li>
            <li>
                <a href="/Event/EventList" aria-expanded="false">
                    <i class="icon-badge menu-icon"></i><span class="nav-text">Etkinlikler</span>
                </a>
            </li>
            <li>
                <a href="/Gallery/GalleryList" aria-expanded="false">
                    <i class="icon-badge menu-icon"></i><span class="nav-text">Galeri</span>
                </a>
            </li>
            <li>
                <a href="/Product/ProductList" aria-expanded="false">
                    <i class="icon-badge menu-icon"></i><span class="nav-text">Yemekler</span>
                </a>
            </li>
            <li>
                <a href="/Reservation/ReservationList/" aria-expanded="false">
                    <i class="icon-badge menu-icon"></i><span class="nav-text">Rezervasyonlar</span>
                </a>
            </li>
            <li>
                <a href="/Service/ServiceList/" aria-expanded="false">
                    <i class="icon-badge menu-icon"></i><span class="nav-text">Hizmetler</span>
                </a>
            </li>
            <li>
                <a href="/Special/SpecialList/" aria-expanded="false">
                    <i class="icon-badge menu-icon"></i><span class="nav-text">Spesiyaller</span>
                </a>
            </li>
            <li>
                <a href="/Testimonial/TestimonialList/" aria-expanded="false">
                    <i class="icon-badge menu-icon"></i><span class="nav-text">Referanslar</span>
                </a>
            </li>

            <li class="nav-label">Siteye Dön!</li>
            <li>
                <a href="/Default/Index" aria-expanded="false">
                    <i class="icon-arrow-left menu-icon"></i><span class="nav-text">Siteye Dön!</span>
                </a>
            </li>
        </ul>
    </div>
</div>
            